name: ibisa-edge
services:
  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - "8086:8086"
    env_file:
      - ./start/influx.env
    volumes:
      - ./influxdb2-data:/var/lib/influxdb2
      - ./influxdb2-config:/etc/influxdb2
    restart: always

  telegraf:
    container_name: telegraf
    image: telegraf
    env_file:
      - ./start/telegraf.env
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:rw
    links:
      - influxdb:influxdb
    restart: always

  kapacitor:
    container_name: kapacitor
    image: kapacitor
    ports:
      - "9092:9092"
    env_file:
      - ./start/telegraf.env
    volumes:
       - ./kapacitorLib:/var/lib/kapacitor
       - ./kapacitor/kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro
       - ./kapacitorTick:/home/kapacitor
    restart: always

  chronograf:
    container_name: chronograf
    image: chronograf
    ports:
      - "8888:8888"
    restart: always

  buffer-link:
    image: ibisalink/buffer:v0.1
    container_name: buffer
    restart: always
    volumes:
      - ./storage:/src/db



